apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.55.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 1.6.1
    repository: https://argoproj.github.io/argo-helm
    alias: argocd-apps
