env:

argo-cd:
  global:
    deploymentStrategy:
      type: RollingUpdate
  crds:
    install: true
  dex:
    enabled: false
  applicationSet:
    enabled: false
  notifications:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      resource.exclusions: |
        - apiGroups:
          - management.cattle.io
          - fleet.cattle.io
          kinds:
          - Cluster
          clusters:
          - "*"
      repositories: |
        - name: stable
          type: helm
          url: https://charts.helm.sh/stable
        - name: argo
          type: helm
          url: https://argoproj.github.io/argo-helm
        - name: fluent
          type: helm
          url: https://fluent.github.io/helm-charts
        - name: traefik
          type: helm
          url: https://helm.traefik.io/traefik
