apiVersion: v1
kind: Service
metadata:
  name: chat-app
  labels:
    app: chat-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: chat-app
  selector:
    app: chat-app
